"""Budgeted Bloomberg snapshot fetch (M6 spec D3-D5).

Stage 1 (this task): monthly PIT S&P 500 membership -> spx_membership.parquet
plus the plain-text universe file the phase-2 config consumes. The entire
membership history costs ONE unique security ("SPX Index").

Every stage consults the UsageLedger BEFORE sending anything, and records
conservatively BEFORE the request goes out (a failed request still counted —
assume Bloomberg metered the attempt).
"""
from __future__ import annotations

import calendar
from datetime import date
from pathlib import Path

import pandas as pd

from btf.data.bloomberg.ledger import LedgerError, UsageLedger
from btf.data.bloomberg.session import SessionLike

INDEX_SECURITY = "SPX Index"
#: Framework symbol under which the benchmark's bars are cached.
BENCHMARK_SYMBOL = "SPX"
MEMBERSHIP_FILENAME = "spx_membership.parquet"


def bloomberg_dir(cache_dir: str | Path) -> Path:
    return Path(cache_dir) / "bloomberg"


def month_ends(start: date, end: date) -> list[date]:
    """Calendar month-end dates in ``[start, end]`` (membership snapshot dates)."""
    out: list[date] = []
    y, m = start.year, start.month
    while (y, m) <= (end.year, end.month):
        me = date(y, m, calendar.monthrange(y, m)[1])
        if start <= me <= end:
            out.append(me)
        y, m = (y + 1, 1) if m == 12 else (y, m + 1)
    return out


def member_symbol(member: str) -> str:
    """``"AAPL UW"`` -> ``"AAPL"`` — drop Bloomberg's exchange code."""
    return member.split()[0]


def security_for(symbol: str) -> str:
    """Framework symbol -> Bloomberg security string."""
    return f"{symbol} US Equity"


def fetch_membership(
    session: SessionLike,
    ledger: UsageLedger,
    cache_dir: str | Path,
    start: date,
    end: date,
    *,
    on: date,
    max_new_per_day: int = 300,
) -> pd.DataFrame:
    """Monthly PIT membership snapshots -> DataFrame(snapshot, symbol) + parquet."""
    if ledger.new_securities([INDEX_SECURITY]) and ledger.allowance(on, max_new_per_day) < 1:
        raise LedgerError(f"daily budget exhausted ({max_new_per_day} new securities)")
    # Record before requesting (conservative: a crash mid-loop still counted).
    ledger.record([INDEX_SECURITY], on)
    rows: list[tuple[pd.Timestamp, str]] = []
    for me in month_ends(start, end):
        for member in session.index_members(INDEX_SECURITY, me):
            rows.append((pd.Timestamp(me), member_symbol(member)))
    frame = pd.DataFrame(rows, columns=["snapshot", "symbol"]).drop_duplicates()
    bdir = bloomberg_dir(cache_dir)
    bdir.mkdir(parents=True, exist_ok=True)
    frame.to_parquet(bdir / MEMBERSHIP_FILENAME)
    return frame


def write_universe_file(membership: pd.DataFrame, path: str | Path) -> list[str]:
    """All-members-ever, sorted — the engine's iterated symbol set (config universe.file)."""
    symbols = sorted(set(membership["symbol"]))
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Point-in-time S&P 500 members (all-ever over the snapshot window).\n"
        "# Generated by scripts/fetch_bloomberg_snapshot.py -- do not edit by hand.\n"
    )
    p.write_text(header + "\n".join(symbols) + "\n")
    return symbols
